package com.udacity.project4.utils

const val REQUEST_FOREGROUND_AND_BACKGROUND_PERMISSION_RESULT_CODE = 33
const val REQUEST_FOREGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 34
const val REQUEST_BACKGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 35
const val REQUEST_TURN_DEVICE_LOCATION_ON = 29